version: "3.9"
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: shipguard
      POSTGRES_PASSWORD: shipguard
      POSTGRES_DB: shipguard
    ports:
      - "5432:5432"
    volumes:
      - shipguard-db:/var/lib/postgresql/data
      - ../backend/sql/schema.sql:/docker-entrypoint-initdb.d/001_schema.sql:ro
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  backend:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    environment:
      PORT: 3001
      JWT_SECRET: ${JWT_SECRET}
      ALLOWED_ORIGINS: http://localhost:5173
      STORAGE_MODE: memory
      QUEUE_MODE: redis
      REDIS_URL: redis://redis:6379
      DATABASE_URL: postgres://shipguard:shipguard@db:5432/shipguard
    ports:
      - "3001:3001"
    depends_on:
      - db
      - redis
  worker:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    command: ["node", "dist/worker.js"]
    environment:
      JWT_SECRET: ${JWT_SECRET}
      PORT: 3001
      STORAGE_MODE: memory
      QUEUE_MODE: redis
      REDIS_URL: redis://redis:6379
      DATABASE_URL: postgres://shipguard:shipguard@db:5432/shipguard
    depends_on:
      - db
      - redis
  frontend:
    build:
      context: ..
      dockerfile: frontend/Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
volumes:
  shipguard-db:
